"use client";
import React, { useState } from 'react';
import { 
    Shield, Bell, Home, CheckCircle2, TrendingUp, Sparkles, 
    AlertCircle, Calendar, ArrowRight, Printer, Share2, HeartPulse,
    ChevronLeft, Activity, ArrowUpRight
} from 'lucide-react';
import Link from 'next/link';

const FuturePrecautions = () => {
    const [remindersSet, setRemindersSet] = useState(false);

    // Mock data for the 3-year outlook
    const healthOutlook = {
        title: "Your 3-Year Health Outlook",
        risks: [
            { name: "Hypertension", level: "Low-Moderate", icon: "💓", color: "text-amber-600 bg-amber-50" },
            { name: "Type 2 Diabetes", level: "Low", icon: "🧬", color: "text-green-600 bg-green-50" },
            { name: "Vitamin D Deficiency", level: "Moderate", icon: "☀️", color: "text-orange-600 bg-orange-50" }
        ],
        precautions: [
            "Monitor blood pressure once a month using a home cuff.",
            "Reduce refined sugar intake by 50% to prevent glycemic spikes.",
            "Increase sun exposure or intake of fatty fish/fortified milk.",
            "Schedule a standard lipid profile check-up annually."
        ],
        tips: [
            "Incorporate 20 mins of brisk walking into your daily routine.",
            "Try the '20-20-20' rule for screen time to reduce eye strain.",
            "Focus on high-fiber foods to improve gut health and metabolism.",
            "Ensure a consistent sleep-wake cycle for hormonal balance."
        ]
    };

    return (
        <div className="min-h-screen bg-[#f8fafc] text-slate-900 font-sans selection:bg-indigo-100 relative overflow-hidden pb-20">
            {/* Background Medical Grid */}
            <div className="absolute inset-0 opacity-[0.03] pointer-events-none" 
                 style={{ backgroundImage: 'radial-gradient(#4f46e5 1px, transparent 1px)', backgroundSize: '30px 30px' }}>
            </div>

            <div className="max-w-4xl mx-auto py-12 px-6 relative z-10">
                {/* Header Action Bar */}
                <div className="flex justify-between items-center mb-8">
                    <Link href="/dashboard" className="flex items-center gap-2 text-slate-500 hover:text-indigo-600 transition-colors font-medium">
                        <ChevronLeft className="w-4 h-4" /> Dashboard
                    </Link>
                    <div className="flex gap-2">
                        <button className="p-2 hover:bg-white rounded-full transition-all shadow-sm border border-slate-200 text-slate-400 hover:text-indigo-600 bg-white/50">
                            <Printer className="w-4 h-4" />
                        </button>
                        <button className="p-2 hover:bg-white rounded-full transition-all shadow-sm border border-slate-200 text-slate-400 hover:text-indigo-600 bg-white/50">
                            <Share2 className="w-4 h-4" />
                        </button>
                    </div>
                </div>

                {/* Hero Title */}
                <div className="text-center mb-12">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 text-indigo-700 text-xs font-bold uppercase tracking-wider mb-4 border border-indigo-100 shadow-sm">
                        <Sparkles className="w-3 h-3" /> AI Analysis Complete
                    </div>
                    <h1 className="text-4xl font-extrabold text-slate-900 mb-3 tracking-tight">
                        {healthOutlook.title}
                    </h1>
                    <p className="text-slate-500 max-w-lg mx-auto leading-relaxed">
                        A personalized roadmap generated by MediGuide AI to help you achieve your long-term wellness goals.
                    </p>
                </div>

                {/* Grid Layout */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    
                    {/* Left Column: Risks & Actions */}
                    <div className="space-y-8">
                        {/* Future Risks Section */}
                        <section className="bg-white rounded-3xl p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 relative overflow-hidden group">
                           <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-50 rounded-full -translate-y-16 translate-x-16 transition-transform group-hover:scale-110 duration-700"></div>
                           
                            <h2 className="text-xl font-bold mb-6 flex items-center gap-3 relative z-10">
                                <TrendingUp className="w-5 h-5 text-indigo-600" />
                                AI Predicted Future Risks
                            </h2>
                            <div className="space-y-4 relative z-10">
                                {healthOutlook.risks.map((risk, i) => (
                                    <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 border border-slate-100 hover:border-indigo-200 transition-all hover:shadow-md cursor-default group/card">
                                        <div className="flex items-center gap-4">
                                            <span className={`w-12 h-12 flex items-center justify-center rounded-xl text-2xl ${risk.color}`}>
                                                {risk.icon}
                                            </span>
                                            <div>
                                                <h4 className="font-bold text-slate-800 text-sm">{risk.name}</h4>
                                                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-widest">{risk.level} Risk</p>
                                            </div>
                                        </div>
                                        <ArrowUpRight className="w-4 h-4 text-slate-300 group-hover/card:text-indigo-400 transition-colors" />
                                    </div>
                                ))}
                            </div>
                        </section>

                        {/* Wellness Tips Section */}
                        <section className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-3xl p-8 shadow-xl text-white relative overflow-hidden">
                            <div className="absolute bottom-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"></div>
                            <h2 className="text-xl font-bold mb-6 flex items-center gap-3">
                                <Activity className="w-5 h-5 text-pink-400" />
                                Health Improvement Tips
                            </h2>
                            <ul className="space-y-4">
                                {healthOutlook.tips.map((tip, i) => (
                                    <li key={i} className="flex gap-4 items-start bg-white/5 p-4 rounded-2xl border border-white/10 hover:bg-white/10 transition-colors group">
                                        <span className="w-6 h-6 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-300 font-bold text-xs shrink-0 group-hover:bg-indigo-500/30 transition-colors">{i+1}</span>
                                        <span className="text-sm text-slate-200 leading-relaxed font-medium">{tip}</span>
                                    </li>
                                ))}
                            </ul>
                        </section>
                    </div>

                    {/* Right Column: Precautions Checklist */}
                    <div className="space-y-8">
                        <section className="bg-white rounded-3xl p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 h-full flex flex-col">
                            <h2 className="text-xl font-bold mb-6 flex items-center gap-3">
                                <Shield className="w-5 h-5 text-green-600" />
                                Preventive Precautions
                            </h2>
                            <div className="space-y-6 flex-1">
                                {healthOutlook.precautions.map((precaution, i) => (
                                    <div key={i} className="flex items-start gap-4 p-5 rounded-2xl border border-slate-50 hover:border-green-100 hover:bg-green-50/30 transition-all group">
                                        <div className="mt-1 w-6 h-6 rounded-full bg-green-50 flex items-center justify-center group-hover:bg-green-100 transition-colors shrink-0">
                                            <CheckCircle2 className="w-4 h-4 text-green-600" />
                                        </div>
                                        <p className="text-sm text-slate-600 leading-relaxed font-medium">
                                            {precaution}
                                        </p>
                                    </div>
                                ))}
                            </div>

                            {/* Sticky Bottom Actions */}
                            <div className="mt-10 pt-8 border-t border-slate-100 space-y-4">
                                <button 
                                    onClick={() => setRemindersSet(!remindersSet)}
                                    className={`w-full py-4 rounded-2xl font-bold transition-all shadow-lg flex items-center justify-center gap-3 active:scale-[0.98] ${
                                        remindersSet 
                                        ? 'bg-green-500 text-white shadow-green-200' 
                                        : 'bg-indigo-600 text-white hover:bg-indigo-700 hover:shadow-indigo-200'
                                    }`}
                                >
                                    {remindersSet ? <Shield className="w-5 h-5" /> : <Bell className="w-5 h-5" />}
                                    {remindersSet ? "Reminders Enabled" : "Set Smart Reminders"}
                                </button>
                                
                                <Link href="/dashboard" className="block">
                                    <button className="w-full py-4 bg-slate-100 text-slate-700 rounded-2xl font-bold hover:bg-slate-200 transition-all flex items-center justify-center gap-3 active:scale-[0.98]">
                                        <Home className="w-5 h-5" />
                                        Back to Home
                                    </button>
                                </Link>
                            </div>
                        </section>
                    </div>
                </div>

                {/* AI Disclaimer Footer */}
                <div className="mt-16 text-center">
                    <div className="inline-flex items-center gap-2 bg-amber-50 px-6 py-3 rounded-full border border-amber-100 mb-6">
                        <AlertCircle className="w-4 h-4 text-amber-600 animate-pulse" />
                        <span className="text-[11px] text-amber-800 font-bold uppercase tracking-tight">
                            AI-Assisted Guidance • Informational Only
                        </span>
                    </div>
                    <p className="text-[10px] text-slate-400 leading-relaxed max-w-xl mx-auto italic">
                        MediGuide AI utilizes predictive modeling to suggest health roadmaps based on your current inputs. This roadmap is for informational purposes and does not constitute a clinical diagnosis. Always consult with a licensed healthcare professional for medical decisions.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default FuturePrecautions;
